events {}

http {

    # -----------------------------
    # AUTH HTTP -> HTTPS
    # -----------------------------
    server {
        listen 80;
        server_name auth.frostbite.co.in;

        return 301 https://$host$request_uri;
    }

    # -----------------------------
    # RESTAURANT HTTP -> HTTPS
    # -----------------------------
    server {
        listen 80;
        server_name restaurant.frostbite.co.in;

        return 301 https://$host$request_uri;
    }

    # -----------------------------
    # AUTH HTTPS
    # -----------------------------
    server {
        listen 443 ssl;
        server_name auth.frostbite.co.in;

        ssl_certificate /etc/nginx/certs/auth_fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/auth_privkey.pem;

        location / {
            proxy_pass http://auth-service:8000;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # -----------------------------
    # RESTAURANT HTTPS
    # -----------------------------
    server {
        listen 443 ssl;
        server_name restaurant.frostbite.co.in;

        ssl_certificate /etc/nginx/certs/restaurant_fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/restaurant_privkey.pem;

        location / {
            proxy_pass http://restaurant-service:8000;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}